name: tdmpc
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.0
  - torchvision
  - pytorch-cuda=12.4
  - pip
  - pip:
    - termcolor
    - omegaconf
    - gymnasium
    - dm-control
    - pandas
    - wandb
    - moviepy
    - imageio
